version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: host

  frontend:
    image: ghcr.io/skkuding/iris-runner-frontend:latest
    container_name: iris-runner-frontend
    ports:
      - "3000:3000"
