name: Build Image

permissions:
  contents: read
  packages: write

on: push

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          {dir: './backend', name: 'backend'},
          {dir: './k8s/pod-manager', name: 'pod-manager'}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.target.dir }}
          push: true
          tags: ghcr.io/skkuding/iris-runner-${{ matrix.target.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
